cache: bundler
language: ruby
rvm:
  - 2.2

before_install:
  - gem update --system
  - gem --version
  - gem install bundler

script: 'bundle exec rspec spec'

after_success:
- CI=true TRAVIS=true coveralls --verbose
